project_name: helmreleaser
release:
  github:
    owner: helmreleaser
    name: helmreleaser
builds:
  - id: helmreleaser
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/helmreleaser/main.go
    ldflags: -s -w
      -X github.com/helmreleaser/helmreleaser/pkg/version.version={{.Version}}
      -X github.com/helmreleaser/helmreleaser/pkg/version.gitSHA={{.Commit}}
      -X github.com/helmreleaser/helmreleaser/pkg/version.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: helmreleaser
    hooks: {}
archives:
  - id: helmreleaser
    builds:
      - helmreleaser
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}-{{ .Major }}.{{ .Minor }}.{{ .Patch }}'
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
